# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.define "base" do |b|
    b.vm.box = "generic/ubuntu2204"
    b.vm.host_name = "base"

    b.vm.provider "virtualbox" do |vb|
      vb.memory = 2048
      vb.cpus = 2
    end
    
    b.vm.network "private_network", ip: "192.168.11.160"

    (1..5).each do |i|
      b.vm.disk :disk, size: "1GB", name: "disk-#{i}"
    end
    b.vm.provision "ansible" do |ansible|
      ansible.playbook = "ansible/create_install_raid.yml"
    end
  end
end
