# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :server => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "server",
        :net => [
           ["192.168.11.150",  2, "255.255.255.0", "mynet"],
        ]
  },
  :client => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "client",
        :net => [
           ["192.168.11.160",  2, "255.255.255.0", "mynet"],
        ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[0]
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      box.vm.provision "shell", inline: <<-SHELL
        mkdir -p ~root/.ssh
        cp ~vagrant/.ssh/auth* ~root/.ssh
        sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
        systemctl restart sshd
        useradd -m -s /bin/bash ansible
        echo "ansible ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
        mkdir -p ~ansible/.ssh
        cp ~vagrant/.ssh/auth* ~ansible/.ssh
        sudo chown -R ansible:ansible ~ansible/.ssh
      SHELL
    end
  end
end