---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      routes:
      - to: 0.0.0.0/0
        via: 192.168.2.129
      - to: 192.168.0.0/24
        via: 192.168.2.129
      - to: 192.168.1.0/24
        via: 192.168.2.129