---
network:
  version: 2
  renderer: networkd
  ethernets:
    eth1:
      routes:
      - to: 0.0.0.0/0
        via: 192.168.255.1
    eth2:
      routes:
      - to: 192.168.2.0/24
        via: 192.168.255.10
    eth3:
      routes:
      - to: 192.168.1.0/24
        via: 192.168.255.6