Vagrant.configure("2") do |config|
    # Every Vagrant development environment requires a box. You can search for
    # boxes at https://vagrantcloud.com/search.
    config.vm.box = "generic/ubuntu2204"
    config.vm.synced_folder ".", "/vagrant"
    
    config.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get -y install linux-oem-22.04d
      sudo reboot
    SHELL
    
    # Определение первой VM
    config.vm.define "NodeMaster" do |vm1|
      vm1.vm.hostname = "NodeMaster"
      vm1.vm.provider "virtualbox" do |vb|
        vb.name = "NodeMasgter"
        vb.memory = "16384"
        vb.cpus = "4"
      end
      vm1.vm.disk :disk, size: "15GB", name: "extra disk"
    end
  end
  