# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :almaX => {
        :box_name => "almalinux/9",
        :vm_name => "almaX",
        :net => [
           ["192.168.11.190",  2, "255.255.255.0", "mynet"],
        ]
  },
  :ubuntuX => {
        :box_name => "generic/ubuntu2204",
        :vm_name => "ubuntuX",
        :net => [
           ["192.168.11.200",  2, "255.255.255.0", "mynet"],
        ]
  }
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|
   
      box.vm.box = boxconfig[:box_name]
      box.vm.host_name = boxconfig[:vm_name]
      
      box.vm.provider "virtualbox" do |v|
        v.memory = 768
        v.cpus = 1
       end

      boxconfig[:net].each do |ipconf|
        box.vm.network "private_network", ip: ipconf[0]
      end

      if boxconfig.key?(:public)
        box.vm.network "public_network", boxconfig[:public]
      end

      if boxconfig[:vm_name] == "almaX"
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          systemctl restart sshd
          cat >> /etc/yum.repos.d/nexus.repo << EOF
[nexus]
name=nexus-almalinux 
baseurl=https://nexus.mda.org.ru/repository/mdalab-yumrepo/
gpgcheck=0
enabled=1
EOF
        SHELL
      else
        box.vm.provision "shell", inline: <<-SHELL  
          mkdir -p ~root/.ssh
          cp ~vagrant/.ssh/auth* ~root/.ssh
          sudo sed -i 's/\#PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
          systemctl restart sshd
          wget -O /etc/apt/trusted.gpg.d/nexus.asc https://raw.githubusercontent.com/menshikoff/linux-admin-pro-home-work/main/month-2/10.%20Размещаем%20RPM%20в%20репозитории/public_key.asc
          cat >> /etc/apt/sources.list.d/nexus.list << EOF
deb https://nexus.mda.org.ru/repository/mdalab-repo/ jammy main
EOF
        SHELL
      end
    end
  end
end